version: 2.1

jobs:
  shanmukh:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push to Docker Hub
          command: |
            docker build -t charan .
            echo "Shanmukh@0410" | docker login -u "shanmukhsreerangam" --password-stdin
            docker tag charan:latest shanmukhsreerangam/project:shanmuk1
            docker push shanmukhsreerangam/project:shanmuk1

workflows:
    jobs:
      - shanmukh